CREATE TABLE `history`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `ACTION_NAME` VARCHAR(100) NOT NULL,
    `TYPE` INT(1) NOT NULL,
    `PRODUCT_ID` INT(11) NOT NULL,
    `QTY` INT(11) NOT NULL,
    `PRICE` DECIMAL(15,2) NOT NULL,
    `ACTIVE_FLAG` INT(1) NOT NULL DEFAULT 1,
    `CREATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);