CREATE TABLE `menu`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `PARENT_ID` INT(11) NOT NULL,
    `URL` VARCHAR(100) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `ORDER_INDEX` INT(11) NOT NULL DEFAULT 0,
    `ACTIVE_FLAG` INT(1) NOT NULL DEFAULT 1,
    `CREATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);