CREATE TABLE `product_in_stock`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `PRODUCT_ID` INT(11) NOT NULL,
    `QTY` INT(11) NOT NULL,
    `ACTIVE_FLAG` INT(1) NOT NULL DEFAULT 1,
    `CREATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);