CREATE TABLE `user_role`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `USER_ID` INT(11) NOT NULL,
    `ROLE_ID` INT(11) NOT NULL,
    `ACTIVE_FLAG` INT(1) NOT NULL DEFAULT 1,
    `CREATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);